source(testthat::test_path("..", "..", "R", "utils.R"), local = FALSE)
source(testthat::test_path("..", "..", "R", "io.R"), local = FALSE)
source(testthat::test_path("..", "..", "R", "demo_data.R"), local = FALSE)
source(testthat::test_path("..", "..", "R", "analysis.R"), local = FALSE)
source(testthat::test_path("..", "..", "R", "plots.R"), local = FALSE)
